### ISSUE TITLE
deepCopy Object with Cyclic Reference

### ISSUE THREAD

**Issue by justinmc** [mbrowne/simpleoo.js#1]
First of all, good set of tools.  I cam here from your SO post (http://stackoverflow.com/a/13635956/257494), and your answer wasn't getting near as much attention as it deserved.

Would it be possible for deepCopy to support an object with a cyclic reference?  For example:

``` javascript
var copyme = {};

var child = {};
var grandchild = {};

// Child references down to grandchild
child.parent = null;
child.child = grandchild;

// Grandchild references back up to child
grandchild.parent = child;
grandchild.child = null;

copyme.thing = child;

deepCopy(copyme) // Infinite loop!

```

I know this is an old repo and perhaps this feature is unnecessary, but I just got to thinking and wanted to start a conversation about it.

**Comment by mbrowne** [comment]
FYI, it turns out there was a bug in the copying of cyclic references - see https://github.com/mbrowne/simpleoo.js/issues/3. I mention this in case you're still using the deepCopy() function and want to update.

**Comment by justinmc** [comment]
Thanks for following up after so long!  I'll keep an eye out for the bug.

**Comment by mbrowne** [comment]
No problem. I'm not sure from your response - you may realize this already - but to be clear, the bug should be fixed now. Thanks for keeping an eye out for any issues with it.
