### ISSUE TITLE
Issue in function deepCopy

### ISSUE THREAD

**Issue by thielsn** [mbrowne/simpleoo.js#3]
I've tried to use your deepCopy function you posted on StackOverflow:
http://stackoverflow.com/a/13333781/5285251

However, it turned out there is a error in L168:
https://github.com/mbrowne/simpleoo.js/blob/master/simpleoo.js#L168

When you return the reference of already visited nodes to support cyclic references, the reference of the source object is returned instead of the reference to the cloned object. The solution is to have a second list with references to the corresponding, already cloned objects and return the reference to them instead.

**Comment by mbrowne** [comment]
Thank you for the bug report and sorry for the delayed reply. This is now fixed. If you have any suggestions for further improvements, feel free to let me know.
